// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/format.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Format by graphviz.
type Format int32

const (
	Format_err    Format = 0
	Format_source Format = 1
	Format_dot    Format = 2
	Format_svg    Format = 3
	Format_png    Format = 4
	Format_jpg    Format = 5
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "err",
		1: "source",
		2: "dot",
		3: "svg",
		4: "png",
		5: "jpg",
	}
	Format_value = map[string]int32{
		"err":    0,
		"source": 1,
		"dot":    2,
		"svg":    3,
		"png":    4,
		"jpg":    5,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_format_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_pb_format_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_pb_format_proto_rawDescGZIP(), []int{0}
}

var File_pb_format_proto protoreflect.FileDescriptor

var file_pb_format_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x41, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12,
	0x07, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x64, 0x6f, 0x74, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x73, 0x76, 0x67, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x70, 0x6e, 0x67, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x6a, 0x70, 0x67, 0x10, 0x05, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_format_proto_rawDescOnce sync.Once
	file_pb_format_proto_rawDescData = file_pb_format_proto_rawDesc
)

func file_pb_format_proto_rawDescGZIP() []byte {
	file_pb_format_proto_rawDescOnce.Do(func() {
		file_pb_format_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_format_proto_rawDescData)
	})
	return file_pb_format_proto_rawDescData
}

var file_pb_format_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_format_proto_goTypes = []interface{}{
	(Format)(0), // 0: pb.Format
}
var file_pb_format_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_format_proto_init() }
func file_pb_format_proto_init() {
	if File_pb_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_format_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_format_proto_goTypes,
		DependencyIndexes: file_pb_format_proto_depIdxs,
		EnumInfos:         file_pb_format_proto_enumTypes,
	}.Build()
	File_pb_format_proto = out.File
	file_pb_format_proto_rawDesc = nil
	file_pb_format_proto_goTypes = nil
	file_pb_format_proto_depIdxs = nil
}
